# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "597fad9e0520214bdfa371cb2953e5df"
name = "Bundle Base"
application_url = "https://bundlebase.imranwebstudio.me"
embedded = true

[build]
# Connect the development store to the CLI tunnel so local edits are visible.
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_contracts/create"
  topics = [ "subscription_contracts/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts,write_app_proxy,write_products,read_publications,write_publications,read_own_subscription_contracts,write_own_subscription_contracts,write_customers,read_customer_payment_methods,read_purchase_options,write_purchase_options,read_rollouts"

[auth]
redirect_urls = [ "https://bundlebase.imranwebstudio.me/auth/callback" ]

[app_proxy]
url = "/api/subscription-plans"
subpath = "bundlify"
prefix = "apps"
