# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "597fad9e0520214bdfa371cb2953e5df"
application_url = "https://bundlify.imranwebstudio.me"
embedded = true
name = "Bundlify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_app_proxy,write_products,read_own_subscription_contracts,write_own_subscription_contracts,write_customers"
# The selected Shopify app must have approved subscription API access.

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://bundlify.imranwebstudio.me/auth/callback" ]

[build]
# Connect the development store to the CLI tunnel so local edits are visible.
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://bundlify.imranwebstudio.me/api/subscription-plans"
subpath = "bundlify"
prefix = "apps"
